### ISSUE TITLE
Question of the local file example

### ISSUE THREAD

**Issue by NNM11** [mmarcon/node-keyring#1]
In the 'node-keyring / example / example-localfile.js ' file, 

The code supports a passing in db file, why the code comment still listed that before running the example, run '//Before running the example, from the command line do the following: ....'
It seems unnecessary if the db was preloaded with data.

Perhaps it is a old comment left over!?

**Comment by mmarcon** [comment]
Yes, I have to admit I have not really updated the README after the first release. It should properly document the API of the module, but it really doesn't... feel free to update it if you have time.

This project was born because I needed it for another project. Then other friends and colleagues found it useful, so I updated it to add more features, but I never really wrote proper documentation.
